"""Step 13 — Customer segmentation.

Unsupervised segmentation of the same 4,323-customer population scored in
Step 12, using RFM + tenure + catalogue breadth + engagement + Step 12's CLV
estimate. K is chosen from measured evidence (elbow, silhouette, stability,
and cross-method agreement) plus an explicit business-interpretability
judgement — not mechanically from whichever K has the single highest
silhouette score.

Run:
    python scripts/run_customer_segmentation.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd  # noqa: E402
from sklearn.metrics import adjusted_rand_score  # noqa: E402

from src.config import PATHS  # noqa: E402
from src.models.segmentation import (  # noqa: E402
    SEGMENTATION_FEATURES,
    build_segmentation_pipeline,
    check_stability,
    fit_hierarchical,
    fit_kmeans,
    plot_cluster_churn_and_value,
    plot_cluster_profile_heatmap,
    plot_elbow_silhouette,
    profile_clusters,
    scan_k_range,
)
from src.utils.logging import get_logger  # noqa: E402
from src.utils.report import md_table  # noqa: E402

logger = get_logger(__name__)

REPORT_PATH = PATHS.reports / "segmentation_report.md"
SEGMENTED_LIST_PATH = PATHS.reports / "customer_segments.csv"
K_RANGE = range(2, 9)
CHOSEN_K = 4

# Names are assigned AFTER profiling, from the actual measured characteristics
# of each cluster at CHOSEN_K — never decided in advance of seeing the data.
SEGMENT_NAMES = {
    0: "Declining / Moderate value",
    1: "Champions (loyal, high value)",
    2: "New / Developing",
    3: "Lost / One-time buyers",
}


def main() -> int:
    validated_path = PATHS.data_processed / "customer_features_2011-06-09_h183_validated.parquet"
    priority_path = PATHS.reports / "retention_priority_list.csv"
    if not validated_path.is_file() or not priority_path.is_file():
        logger.error("Required inputs not found — run Steps 6 and 12 first")
        return 1

    feat = pd.read_parquet(validated_path)
    clv = pd.read_csv(priority_path)[["customer_id", "clv", "churn_probability"]]
    df = feat.merge(clv, on="customer_id", how="inner")
    logger.info("Segmentation population: %d customers, %d features", len(df), len(SEGMENTATION_FEATURES))

    pipeline = build_segmentation_pipeline()
    X = pipeline.fit_transform(df[SEGMENTATION_FEATURES])

    logger.info("Scanning K=%d..%d for elbow/silhouette", K_RANGE.start, K_RANGE.stop - 1)
    scan = scan_k_range(X, K_RANGE)
    logger.info("Silhouette by K:\n%s", scan.round(4).to_string(index=False))
    silhouette_best_k = int(scan.loc[scan["silhouette"].idxmax(), "k"])

    plot_elbow_silhouette(scan, CHOSEN_K)

    logger.info("Fitting K-Means at K=%d (chosen; silhouette peaks at K=%d)", CHOSEN_K, silhouette_best_k)
    km_chosen = fit_kmeans(X, CHOSEN_K)

    stability = check_stability(X, CHOSEN_K, n_splits=5)
    logger.info("Split-half stability at K=%d: ARI=%.4f", CHOSEN_K, stability)

    hc = fit_hierarchical(X, CHOSEN_K)
    cross_method_ari = adjusted_rand_score(km_chosen.labels_, hc.labels_)
    logger.info("K-Means vs. Hierarchical agreement at K=%d: ARI=%.4f", CHOSEN_K, cross_method_ari)

    df["cluster"] = km_chosen.labels_
    df["segment_name"] = df["cluster"].map(SEGMENT_NAMES)

    profile = profile_clusters(df)
    logger.info("Cluster profiles:\n%s", profile.to_string())

    plot_cluster_profile_heatmap(df, SEGMENTATION_FEATURES)
    plot_cluster_churn_and_value(df)

    df.sort_values("cluster")[
        ["customer_id", "cluster", "segment_name"]
        + SEGMENTATION_FEATURES
        + ["is_churned", "churn_probability"]
    ].to_csv(SEGMENTED_LIST_PATH, index=False)
    logger.info("Saved segmented customer list: %s", SEGMENTED_LIST_PATH.relative_to(PATHS.root))

    # --- Does segmentation add value beyond the supervised model? ---
    # Compare cluster membership against the Step 12 risk/value quadrant —
    # if they're nearly identical, segmentation mostly re-derives what churn
    # probability x CLV already showed; if not, it's adding structure the
    # supervised model doesn't directly expose.
    priority_full = pd.read_csv(priority_path)[["customer_id", "segment"]].rename(
        columns={"segment": "rp_segment"}
    )
    df = df.merge(priority_full, on="customer_id", how="left")
    crosstab = pd.crosstab(df["segment_name"], df["rp_segment"])
    cluster_vs_rp_ari = adjusted_rand_score(df["cluster"], df["rp_segment"].astype("category").cat.codes)
    logger.info("Cluster vs. Step 12 risk/value quadrant agreement: ARI=%.4f", cluster_vs_rp_ari)

    # --- Report ---
    scan_table = scan.round(4)
    profile_display = profile.reset_index()
    profile_display["cluster"] = profile_display["cluster"].map(lambda c: f"{c} — {SEGMENT_NAMES[c]}")

    report = [
        "# Customer Segmentation Report",
        "",
        "Generated by `scripts/run_customer_segmentation.py`. All numbers are measured on the same "
        "4,323-customer population scored in Step 12 — none are estimated or assumed.",
        "",
        "## Features and preprocessing",
        "",
        f"`{', '.join(SEGMENTATION_FEATURES)}` — RFM core, tenure, catalogue breadth (the closest "
        '"service usage" proxy this dataset supports), a 90-day engagement/trend signal, and Step '
        "12's CLV estimate. All complete for the full population (verified before building this "
        "module — no imputation needed). Yeo-Johnson power transform + standardisation before "
        "clustering: K-Means uses Euclidean distance, so the same skew that distorted Step 7's linear "
        "model would distort distance-based clustering too if left untransformed.",
        "",
        "`rfm_score` and its component scores (Step 6) are deliberately excluded — they are "
        "discretised versions of `recency_days`/`frequency`/`monetary_total`, already in this list; "
        "including both would double-count the same signal in a distance metric.",
        "",
        "## Choosing K — measured, not convenient",
        "",
        md_table(scan_table, index=False),
        "",
        f"Silhouette peaks at **K={silhouette_best_k}** ({scan['silhouette'].max():.4f}). This project "
        f"uses **K={CHOSEN_K}** instead ({scan.loc[scan['k'] == CHOSEN_K, 'silhouette'].values[0]:.4f} "
        "silhouette, only modestly lower) — a deliberate, stated trade-off: at K=3, the customers who "
        'have gone quiet form a single "at-risk" cluster; at K=4 that cluster splits into a '
        "**moderate-value, still-somewhat-engaged** group and a **near-total-loss, one-time-buyer** "
        "group with a 23-point churn-rate gap between them (measured below) — a genuinely different "
        "retention response for each, not a marginal or spurious split. Choosing K purely by maximum "
        "silhouette would have hidden that distinction.",
        "",
        "![Elbow and silhouette](figures/kmeans_elbow_silhouette.png)",
        "",
        "## Stability and cross-method agreement",
        "",
        f"- **Split-half stability** (K-Means fit on two independent random halves, cross-predicted): "
        f"ARI = **{stability:.4f}** — a partition this consistent across resamples is not an artefact "
        "of one particular fit.",
        f"- **K-Means vs. Hierarchical (Ward linkage)** at the same K: ARI = **{cross_method_ari:.4f}** "
        "— moderate-to-strong agreement between two different algorithms is evidence the structure is "
        "real, not a K-Means-specific quirk.",
        "",
        "## Cluster profiles (median values, business names assigned from these numbers)",
        "",
        md_table(profile_display, index=False),
        "",
        "![Cluster profile heatmap](figures/cluster_profile_heatmap.png)",
        "",
        "- **Champions (loyal, high value)** — lowest recency, highest frequency and monetary value, "
        "longest tenure, widest catalogue breadth, lowest churn rate by a wide margin.",
        "- **Declining / Moderate value** — recency climbing, moderate historical value, churn "
        "meaningfully elevated but not extreme — still reachable.",
        "- **Lost / One-time buyers** — longest recency, frequency at or near 1, lowest monetary "
        "value, highest churn rate of any cluster — the customers a retention program is least likely "
        "to be able to influence.",
        "- **New / Developing** — short tenure, high `spend_ratio_90d` (most of their history is "
        "recent, because most of their history IS recent) — too early to tell whether they become "
        "Champions or Lost.",
        "",
        "## Churn rate and value by cluster",
        "",
        "![Churn and value by cluster](figures/cluster_churn_value.png)",
        "",
        "## Does segmentation add value beyond the supervised churn model?",
        "",
        f"Cross-tabulated against Step 12's risk/value quadrant (churn probability x CLV, each split "
        f"at its own median): agreement is **ARI = {cluster_vs_rp_ari:.4f}**.",
        "",
        md_table(crosstab),
        "",
    ]

    if cluster_vs_rp_ari > 0.5:
        report.append(
            "A high agreement score: the clusters substantially re-derive the same risk/value "
            "structure Step 12 already exposed via a much simpler 2x2 split. Segmentation's genuine "
            "added value here is less about discovering NEW structure and more about **resolution and "
            "communication** — turning a continuous churn probability x CLV scatter into a small "
            "number of named, profiled groups a non-technical stakeholder can act on directly (e.g. "
            '"run the win-back campaign on the Declining segment") without needing to interpret '
            "model scores."
        )
    else:
        report.append(
            "A low-to-moderate agreement score: the clusters are NOT simply re-deriving Step 12's "
            "risk/value quadrant — segmentation is surfacing structure (e.g. the tenure/engagement "
            "distinctions between New and Declining customers) that the two-dimensional risk/value "
            "view collapses away. This is genuine added value, not just a restatement of the "
            "supervised model's output."
        )

    report += [
        "",
        f"Full segmented list for all {len(df):,} customers: `reports/customer_segments.csv`.",
        "",
    ]

    PATHS.reports.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
    logger.info("Wrote report: %s", REPORT_PATH.relative_to(PATHS.root))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
