"""Step 11 — Explainable AI with SHAP.

Global explanations (which features drive the model overall) and local
explanations (why THIS customer got THIS prediction), built on the Step 9
tuned XGBoost model. See src/explainability.py's module docstring for why
SHAP explains the pre-calibration model while probabilities shown come from
the Step 10 calibrated model.

Run:
    python scripts/run_shap_explainability.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import joblib  # noqa: E402
import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from src.config import PATHS  # noqa: E402
from src.explainability import (  # noqa: E402
    compute_shap_explanation,
    explain_customer,
    plot_shap_bar_importance,
    plot_shap_dependence,
    plot_shap_summary,
)
from src.models.preprocessing import split_X_y_tree  # noqa: E402
from src.utils.logging import get_logger  # noqa: E402
from src.utils.report import md_table  # noqa: E402

logger = get_logger(__name__)

REPORT_PATH = PATHS.reports / "shap_explainability_report.md"
TUNED_MODEL_PATH = PATHS.models / "xgboost_tuned.joblib"
FINAL_MODEL_PATH = PATHS.models / "final_churn_model.joblib"
N_DEPENDENCE_PLOTS = 3


def main() -> int:
    test_path = PATHS.data_processed / "test.parquet"
    if not TUNED_MODEL_PATH.is_file() or not FINAL_MODEL_PATH.is_file():
        logger.error("Models not found — run Steps 9 and 10 first")
        return 1

    test_df = pd.read_parquet(test_path)
    X_test, y_test = split_X_y_tree(test_df)

    tuned_pipeline = joblib.load(TUNED_MODEL_PATH)
    final_model = joblib.load(FINAL_MODEL_PATH)

    logger.info("Computing SHAP values for %d test customers", len(X_test))
    explanation, X_transformed = compute_shap_explanation(tuned_pipeline, X_test)

    # --- Global ---
    plot_shap_summary(explanation)
    importance_path = plot_shap_bar_importance(explanation)

    mean_abs = np.abs(explanation.values).mean(axis=0).astype(np.float64)
    importance_table = (
        pd.DataFrame({"feature": explanation.feature_names, "mean_abs_shap": mean_abs})
        .sort_values("mean_abs_shap", ascending=False)
        .reset_index(drop=True)
    )
    top_features = importance_table["feature"].head(N_DEPENDENCE_PLOTS).tolist()
    logger.info("Top %d features by mean |SHAP|: %s", N_DEPENDENCE_PLOTS, top_features)

    dependence_paths = []
    for feature in top_features:
        path = plot_shap_dependence(explanation, feature)
        dependence_paths.append((feature, path))
        logger.info("Saved dependence plot: %s", path.relative_to(PATHS.root))

    # --- Local: three representative customers ---
    test_proba = final_model.predict_proba(X_test)[:, 1]
    test_df = test_df.assign(_proba=test_proba)

    highest_risk_id = int(test_df.loc[test_df["_proba"].idxmax(), "customer_id"])
    lowest_risk_id = int(test_df.loc[test_df["_proba"].idxmin(), "customer_id"])
    borderline_id = int(test_df.iloc[(test_df["_proba"] - 0.5).abs().argsort().iloc[0]]["customer_id"])

    example_ids = {
        "Highest predicted risk": highest_risk_id,
        "Lowest predicted risk": lowest_risk_id,
        "Borderline (~50%)": borderline_id,
    }

    local_explanations = {}
    for label, cid in example_ids.items():
        result = explain_customer(cid, test_df, tuned_pipeline, final_model)
        local_explanations[label] = result
        logger.info("%s (customer %d): %.1f%% churn probability, %s risk",
                     label, cid, result["churn_probability"] * 100, result["risk_level"])

    # --- Report ---
    report = [
        "# SHAP Explainability Report",
        "",
        "Generated by `scripts/run_shap_explainability.py`. All numbers are computed on the actual "
        "held-out test split — none are estimated or assumed.",
        "",
        "## Methodology: which model SHAP explains, and why",
        "",
        "The project's final model (`models/final_churn_model.joblib`, Step 10) is a "
        "`CalibratedClassifierCV` — internally 5 cloned pipelines, one per calibration fold. SHAP's "
        "`TreeExplainer` needs a single tree ensemble to walk, not a calibration wrapper around "
        "several, so it cannot be applied to that object directly.",
        "",
        "- **SHAP attribution** (which features drive the decision) is computed on the "
        "pre-calibration Step 9 tuned XGBoost pipeline. Calibration rescales the final probability "
        "for reliability; it does not change which features the underlying trees split on.",
        "- **The displayed probability** for every customer below comes from the calibrated final "
        "model, so it matches what the Step 10 business threshold and the Step 14 API will show.",
        "",
        "## What SHAP values mean — and do not mean",
        "",
        "A SHAP value is a feature's contribution to THIS model's THIS prediction, relative to the "
        "average prediction — a precise accounting number, not a statement about the real world.",
        "",
        "- Values are in **log-odds (margin) space** (`TreeExplainer`'s default): positive pushes "
        "the model's score toward churn, negative pushes toward retention. The magnitude is not "
        "directly \"N percentage points of probability.\"",
        "- **A high-impact feature is not a cause of churn.** SHAP explains the model, not the "
        "customer's real decision — it cannot separate a genuine driver from a feature that merely "
        "correlates with one. `recency_days` (below) is a case in point: it is mechanically close "
        "to how churn is *labelled* (Step 3/5/9 all discuss this), which is exactly why it dominates "
        "— that is expected, not evidence of a causal effect. Causal claims need the experimental "
        "design in Step 20, not an explainability method applied to an observational model.",
        "",
        "## Global feature importance",
        "",
        md_table(importance_table.head(15).round(4), index=False),
        "",
        "![SHAP summary](figures/shap_summary.png)",
        "",
        "![SHAP importance](figures/shap_importance.png)",
        "",
    ]

    for feature, path in dependence_paths:
        report += [f"### Dependence: `{feature}`", "", f"![{feature}](figures/{path.name})", ""]

    report += [
        f"**`rfm_score` dominates by a wide margin** (mean |SHAP| {importance_table.iloc[0]['mean_abs_shap']:.4f}, "
        f"nearly 3x the runner-up `recency_days` at {importance_table.iloc[1]['mean_abs_shap']:.4f}) — and the "
        "dependence plot above shows an almost perfectly monotonic relationship, exactly matching the clean "
        "gradient Step 6 found (79.6% churn at score 3 down to 2.8% at score 14).",
        "",
        "**This is a striking contrast with Step 7's Logistic Regression**, where `rfm_score` had the single "
        "strongest UNIVARIATE correlation with churn of any feature, yet its multivariate coefficient nearly "
        "vanished and flipped sign — absorbed by its own raw ingredients (`recency_days`, `frequency`, "
        "`monetary_total`) still present in the linear model. XGBoost's trees don't have that problem: gradient "
        "boosting can freely choose to split on the clean, low-cardinality `rfm_score` (values 3-14) instead of "
        "its noisier continuous components whenever that split is more useful, without being penalised for "
        "correlated inputs the way a linear coefficient estimate is. The same feature is nearly worthless to "
        "one model family and the single most important input to another — a concrete illustration of why "
        "Step 8 measured multiple model families rather than trusting one's feature ranking.",
        "",
        "## Local explanations — three representative customers",
        "",
        "Red bars push the prediction toward churn, blue bars push toward retention — the same "
        "colour convention as every churn-outcome chart since Step 5.",
        "",
    ]
    for label, result in local_explanations.items():
        report += [
            f"### {label}: customer {result['customer_id']}",
            "",
            f"**{result['narrative']}**",
            "",
            f"![Customer {result['customer_id']}](figures/shap_local_{result['customer_id']}.png)",
            "",
        ]

    report += [
        "## Using `explain_customer()` elsewhere",
        "",
        "```python",
        "from src.explainability import explain_customer",
        "",
        "result = explain_customer(customer_id, test_df, tuned_pipeline, final_model)",
        "print(result['narrative'])",
        "```",
        "",
        "This same function is what Step 14's `/predict/explain` API endpoint calls — the "
        "explanation logic is written once here, not reimplemented in the API layer.",
        "",
    ]

    PATHS.reports.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(report), encoding="utf-8")
    logger.info("Wrote report: %s", REPORT_PATH.relative_to(PATHS.root))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
